name: CI Checks
on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get real merge base
        run: |
          # Set the base reference: if the event is a pull_request, use its base branch; otherwise, default to "main"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
          fi
          
          # Expose these as environment variables for Turborepo
          echo "TURBO_SCM_BASE=$BASE_SHA" >> $GITHUB_ENV
          echo "TURBO_SCM_HEAD=$HEAD_SHA" >> $GITHUB_ENV
          
          echo "base: $BASE_SHA"
          echo "head: $HEAD_SHA"

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run ci

      - name: Get affected packages paths
        id: changed_packages
        if: github.ref != 'refs/heads/main'
        run: |
          echo "base: $TURBO_SCM_BASE"
          echo "head: $TURBO_SCM_HEAD"

          packages=$(pnpx turbo ls --affected --output=json \
            | jq -r '.packages.items[].path' \
            | paste -sd ", " -
          )

          if [ -z "$packages" ]; then
            echo "No packages changed"
            echo "packages=" >> $GITHUB_OUTPUT
          else
            echo "Detected packages: $packages"
            echo "packages=$packages" >> $GITHUB_OUTPUT
          fi

      - name: Publish preview releases
        if: github.ref != 'refs/heads/main' && steps.changed_packages.outputs.packages != ''
        run: pnpx pkg-pr-new publish ${{ steps.changed_packages.outputs.packages }}
