name: CI Checks
on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run ci

      - name: Get real merge base
        run: |
          # Ensure we have base branch locally
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # Compute the common ancestor between HEAD and base
          MERGE_BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})

          # Expose these as environment variables for Turborepo
          echo "TURBO_SCM_BASE=$MERGE_BASE" >> $GITHUB_ENV
          echo "TURBO_SCM_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
          echo "base: $TURBO_SCM_BASE"
          echo "head: $TURBO_SCM_HEAD"
      - name: Get affected packages paths
        id: changed_packages
        if: github.ref != 'refs/heads/main'
        run: |
          echo "base: $TURBO_SCM_BASE"
          echo "head: $TURBO_SCM_HEAD"

          packages=$(pnpx turbo ls --affected --output=json \
            | jq -r '.packages.items[].path' \
            | paste -sd ", " -
          )

          if [ -z "$packages" ]; then
            echo "No packages changed"
            echo "packages=" >> $GITHUB_OUTPUT
          else
            echo "Detected packages: $packages"
            echo "packages=$packages" >> $GITHUB_OUTPUT
          fi

      - name: Publish preview releases
        if: github.ref != 'refs/heads/main' && steps.changed_packages.outputs.packages != ''
        run: pnpx pkg-pr-new publish ${{ steps.changed_packages.outputs.packages }}
